### ISSUE TITLE
Cannot start snake.py

### ISSUE THREAD

**Issue by pkrog** [Marc-Samba/git#21]
I've tried to start the game with `python snake.py` but it fails:
```
Namespace(bg_color_1=(0, 0, 0), bg_color_2=(255, 255, 255), height=300, width=400, fps=10, fruit_color=(255, 0, 0), snake_color=(0, 255, 0), snake_length=None, tile_size=20, gameover_on_exit=None, debug=None)
Traceback (most recent call last):
  File "/Users/pierrick/data/py-mines-2023/marc/git/snake.py", line 245, in <module>
    main()
  File "/Users/pierrick/data/py-mines-2023/marc/git/snake.py", line 212, in main
    read_args()
  File "/Users/pierrick/data/py-mines-2023/marc/git/snake.py", line 57, in read_args
    raise ValueError
ValueError
```
It seems you have command line arguments that have no default value defined.
I tried to guess the values to give to --debug and --gameover-on-exit, but without success.
Please define default values, and define --debug and --gameover-on-exit as flag command line options (i.e.: they must not take a value).

**Comment by pkrog** [comment]
Please correct urgently.
